var employees=[
{name:"Saman", personality: "quiet", picture: "http://centerforopenscience.org/static/img/people/ehsan.jpg"},
{name:"Erin", personality: "talkative", picture: "http://centerforopenscience.org/static/img/people/braswell.JPG"},
{name:"Sam", personality: "quiet", picture: "http://centerforopenscience.org/static/img/people/chrisinger.jpg"},
{name:"Nan", personality: "quiet", picture: "http://centerforopenscience.org/static/img/people/chen.jpg"},
{name:"Michael", personality: "talkative", picture: "http://centerforopenscience.org/static/img/people/michael.jpg"},
{name:"Harry", personality: "talkative", picture: "http://centerforopenscience.org/static/img/people/rybaki.jpg"},
{name:"Brian G.", personality: "talkative", picture: "http://centerforopenscience.org/static/img/people/geiger.jpg"},
{name:"Bryan G.", personality: "quiet", picture: "http://centerforopenscience.org/static/img/people/gorges.jpg"},
{name:"Billy", personality: "talkative", picture: "http://centerforopenscience.org/static/img/people/hunt.jpg"},
{name:"Andy", personality: "quiet", picture: "http://centerforopenscience.org/static/img/people/boughton.jpg"},
{name:"Lyndsy", personality: "talkative", picture:"http://centerforopenscience.org/static/img/people/simon.jpg"},
{name:"Chris", personality: "quiet", picture: "http://centerforopenscience.org/static/img/people/seto.jpg"},
{name:"Caner", personality: "talkative", picture: "http://centerforopenscience.org/static/img/people/uguz.jpg"},
{name:"Andrew", personality: "talkative", picture: "http://centerforopenscience.org/static/img/people/sallans.jpg"},
{name:"Jeff", personality: "talkative", picture: "http://centerforopenscience.org/static/img/people/spies.jpg"},
{name:"Brian N.", personality: "talkative", picture: "http://centerforopenscience.org/static/img/people/nosek.jpg"},
{name:"Fabian", personality: "quiet", picture: "http://centerforopenscience.org/static/img/people/feilitzsch.jpg"},
{name:"Steve", personality: "quiet", picture: "http://centerforopenscience.org/static/img/people/loria.jpg"},
];
